### ISSUE TITLE
all types of errors running npm test after install

### ISSUE THREAD

**Issue by jmaclabs** [e14n/pump.io#1008]
After following the installation guide, I ran `npm test` and not one of the "tests" seemed to pass.

Also, I noticed that the build status is failed.

Is this just a temporary build bug or is there something more serious going on?

**Comment by larjona** [comment]
Much work has been done to make pump.io tests pass, but I don't know if the tests referenced here are the same.

Is this still an issue?

**Comment by strugee** [comment]
At the time this was filed I believe tests were definitely failing, but have since been fixed. Furthermore IIRC the DTrace problem referenced in https://github.com/e14n/pump.io/issues/1008#issuecomment-39285961 was a problem in a dependency which has since been fixed upstream.

Closing due to the above, but if anyone still sees these problems, ping me or @larjona and we'll reopen
