### ISSUE TITLE
Change email in pumprock.net

### ISSUE THREAD

**Issue by phls** [e14n/pump.io#1081]
Hi,
I have an account in pumprock.net but I don't know what email I had put there.
How can I see what email I used?
And how can I change the email?

Thanks,

**Comment by jankusanagi** [comment]
You can't change the e-mail address at this time, but since you weren't asked for on when creating the account, there's really nothing to change. The web interface doesn't provide a way to either add or change an e-mail address, yet.

You could associate an e-mail address with your account using the admin tools, if you had your own server.

**Comment by jankusanagi** [comment]
Ok, update!

Now you can set or change your e-mail address using the [development version of the Dianara client](https://gitlab.com/dianara/dianara-dev). The only problem is that you'll need to build it yourself from source, unless you wait for the v1.3.1 release =)

**Comment by larjona** [comment]
@phls Could you change your email with Dianara? If yes, please close this issue.
Thanks for your support!
