### ISSUE TITLE
Adopt a Code of Conduct

### ISSUE THREAD

**Issue by strugee** [e14n/pump.io#1142]
We should have a Code of Conduct that protects people in the pump.io community from discrimination. The TODO Group's [Open Code of Conduct][1] seems particularly good to me, if no one has any other suggestions.

I should mention that I haven't seen anything at all to think that we'd need this, but I'm a firm believer that all free software communities should have Codes of Conduct, just in case. I'd be happy to prepare a PR.

CC @evanp

 [1]: http://todogroup.org/opencodeofconduct/

**Comment by jart** [comment]
The TODO Group's code of conduct says that excluding contributors on the basis of merit is "discrimination." This makes it fundamentally incompatible with open source values, e.g. meritocracy.

I'd like to propose an alternative code of conduct, which is politically neutral. It's called the FTFLCOC: https://gist.github.com/jart/f274d8dc156811a46b22 Please consider adopting it.

**Comment by strugee** [comment]
@jart I disagree, because the way that you handle the situation matters. Obviously we're not going to take crappy code. But we can either point out ways for the contributor to improve, or we can [pull a Linus][1] (I'd link you to the [original archive][2], but it seems broken currently). This is why "discrimination based on merit" is important.

 [1]: https://plus.google.com/+LennartPoetteringTheOneAndOnly/posts/J2TZrTvu7vd
 [2]: https://lkml.org/lkml/2012/7/6/495

**Comment by jart** [comment]
Linus profanely flaming people for their inadequacies has little to do with discrimination based on merit. The people Linus flames have a tremendous amount of merit. So Linus' actions would be considered problematic due to the profane flaming, which is covered by other aspects of a code of conduct.

It's a nice thing to help people improve when they don't have merit. Most people will be polite, and at the very least point a man to books he can read if he has no skills whatsoever. If you think projects should be obliged to politely do that, rather than screaming at them and banning them, well, I think you've got a perfectly reasonable point of view.

However I'd like to hear your honest opinion on something. What about the people who absolutely zero interest in acquiring the technical skills necessary to contribute to an open source project, yet still want to participate? Should a CoC guarantee *any* individual the right to participate in a software project, so long as he/she follows the CoC?

You may wonder, why would someone participate in an open source project project if he/she isn't writing code? What else is there left to do? Well, there's always moderating the community and shaping project policies. So I ask you this, as one engineer to another: do you really want people who aren't engineers to be the ones in charge of those things?

**Comment by cwebber** [comment]
@jart, it hasn't been my experience that a Code of Conduct means that people who aren't "doing the work" aren't in charge.  It's also not incompatible with a "BDFL" type position or etc, or whatever governance structure we chose.  (Though, I will note that I don't consider coding to be the only important task.)

However, though I'm a big code of conduct supporter, though I do agree that the challenges against "merit" driven development in communities are sometimes misaligned, since as you said, people who do the work are the ones that make free software projects happen (Stefano Zacchiroli has phrased this as "do-ocracy").  So maybe another Code of Conduct should be chosen.

I think the Contributor Covenant looks pretty good: http://contributor-covenant.org/version/1/4/code_of_conduct.txt  It's also used by some projects I like.

What do people think?

**Comment by skellat** [comment]
So we're painting the bike rack mauve then?

**Comment by akuckartz** [comment]
As an observer I wonder why this discussion is taking place. I personally am not very interested in it.

**Comment by strugee** [comment]
> Linus profanely flaming people for their inadequacies has little to do with discrimination based on merit. The people Linus flames have a tremendous amount of merit. So Linus' actions would be considered problematic due to the profane flaming, which is covered by other aspects of a code of conduct.

In the case I linked to, yes (which makes me realize I probably should've picked a different case), but Linus has been known to flame less experienced developers, too.

> However I'd like to hear your honest opinion on something. What about the people who have absolutely zero interest in acquiring the technical skills necessary to contribute to an open source project, yet still want to participate? Should a CoC guarantee any warm body the right to participate in a software project, so long as he/she follows the CoC?

No, I'd consider that a [help vampire][1]

> So I ask you this, as one engineer to another: do you really want the people who aren't engineers to be the ones in charge of those things?

I think it depends a lot on the community. For this one, since it's so small, I'd say no. But in (for example) GNOME, I'd say yeah - leadership should be representative of all kinds of people, and that means UX people, QA people, artists, etc. in addition to programmers.

> I personally don't want to be quietly writing code while the lawyers and politicians run the show, and tell me what I can and can't say. I firmly believe that the people who do the work should be the ones in charge.

Yes. I'm with you here. I think we're talking across each other - you're saying that you shouldn't be in a leadership position without having merit (which I agree with), whereas I'm saying that you shouldn't exclude someone who doesn't know what they're doing but is genuinely trying to help.

My impression is that we both actually 100% agree with each other. That being said, since we've had to have this entire conversation about it, it's obvious that the TODO Group's CoC is too ambiguous - let's pick a new one :)

 [1]: http://slash7.com/2006/12/22/vampires/

**Comment by strugee** [comment]
@cwebber sounds great.

**Comment by strugee** [comment]
@akuckartz because the participants in this thread would rather have a smaller but safer community rather than a larger but more dangerous (for marginalized people) community - or in other words, they value individual safety over technical contributions. A Code of Conduct sends an explicit message to participants, which is necessary because the norm in free software is currently the reverse (valuing technical contributions over individual safety).

**Comment by akuckartz** [comment]
> the norm in free software is currently the reverse (valuing technical contributions over individual safety).

I doubt there exists any empirical evidence for a prevalence of threats to such "individual safety".

**Comment by cwebber** [comment]
So, we're seeing a bit of communication here from people who are outside of the community, and as for all the talk of founders should rule and implementers should have a say, @strugee *is* an implementer, and the founder we're really waiting on in this conversation is @evanp.  So please, outside participants, let us have that conversation.

**Comment by arotter** [comment]
I just hope you all got every single one of your public social network accounts sanitized. Would be a shame if someone found anything _problematic_ in them, right?

→ https://github.com/opal/opal/issues/941

**Comment by nsymtex** [comment]
We really need to lobby Github to auto include a CoC of conduct in every project by default.

It's 2016. Every project needs one. We finally need to rid this site of its toxic masculinity. We need to control speech outside of projects in order to make everyone feel safe to contribute, because who wants to contribute to a project with a known anti-feminist rape apologist? Everyone needs to feel like anything they say or do outside of contribute their time and energy to open source projects can be used to attack and excommunicate them from their own projects.

That way the whole site can be a safe space.

Anyone who disagrees with adding a CoC is a bigoted transphobic misogynistic perpetuator of the patriarchy. Good riddance.

We should all do our part and begin to search through the timelines of contributors to make sure that they are ideologically pure. Please post any potential CoC violations here so we can begin to deal with the people who are potentially a problem to this project.

I'm starting with strugee who goes by strugee2 on twitter

I've already found over a dozen highly problematic, ideologically impure, unsafe tweets (which I've already archived and will present once more evidence has been collected) that expose him as really not a good person for this project, though he gets points for suggesting such a progressive CoC it was clearly a move to make others not think it was necessary for us to investigate his own bigoted anti-feminist misogyny. Though a clever move, us true feminists are superior. He even calls himself a proud feminists when we all know no cis het white male can never be a feminist, and only ever an ally. Only a manipulator abuser would lie like that. Red flags all over the place. I urge you all to do your part in this investigation.

**Comment by nsymtex** [comment]
It appears strugee2 is already attempting to delete evidence as I was archiving tweet it archived 404 instead. I will work faster. Do not worry I do other archives. I will share once I have collected more older tweets that reveal what kind of person he really is in order to make this project better for everyone to feel safe. Please do your part and investigate other contributes so that we can hold them accountable for breaking CoC.

@cwebber No, it is not the place of privileged white males to decide, it should be the women and minorities who decide because we are the ones being oppressed by these oppressors, and besides people who disagree should be banned from contributing.

**Comment by h4rm0n1c** [comment]
That's a winner of an idea: comb through the timelines and accounts of anyone who pushes the various Codes of Conduct out there.
(that are primarily designed to entrench power into a small clique, this is an invade, divide and conquer strategy)

Should be easy to find blatant hypocrisy (such as treating straight white men like shit because "progressive stack, lol") and use that as evidence to disqualify their "suggestion" as being ideologically motivated.

I'd argue that personal power agendas and social politics have no merit in open source projects, they serve no purpose other than to engage in that annoying cancerous tribalism that goes with ideological infection.

After all, merit rules supreme in open source, all we have to do is show that any suggested code of conduct has NO merit under the logic stated above and therefore, is still fundamentally incompatible with open source.

**Comment by sstewartgallus** [comment]
@strugee The open code of conduct is not open: https://github.com/todogroup/opencodeofconduct/issues/103

**Comment by Paromika** [comment]
Perhaps consider a [Code of Merit](https://github.com/rosarior/Code-of-Merit) instead. Much better than a "Code" of Conduct.

**Comment by jart** [comment]
Wow the Code of Merit is really cool! Thanks for sharing. I just read it and it seems very much in tune with the authentic hacker values that software engineers have tacitly understood for decades.

I think formalizing old school open source hacker values is a good thing. Why? Because our values are the best. Seriously. We have good reason to be proud of ourselves as engineers. We invented the first international, colorblind, post-monetary, and meritocratic society in all of human history. No other culture has ever come close to achieving *even one* of those things. But hackers on the Internet did them all. Because that's just what happens when software engineers who *do the work* are the ones in charge.

That's why I don't really take political agitators very seriously. What gives outsiders the right to condemn our beautiful culture? They tell us that we need to change. But if they were wise, they would be learning from us instead.

**Comment by vibhavp** [comment]
Whether "reverse-racism" or "reverse-sexism" is real or not is a politically charged debate. To push for a code of conduct which doesn't recognize it is tantamount to pure agenda pushing.
Plus, most CoCs do not attempt to properly define how or when project member/maintainer is representing the project, which can (and has) times lead to members being booted from the project [just because some of their political affiliations aren't in-line with what the CoC says](https://github.com/opal/opal/issues/941). Let's treat individuals as individuals, and adopting a individualistic/politically neutral like the Code of Merit is one way of that.

**Comment by graspee** [comment]
"Whether "reverse-racism" or "reverse-sexism" is real or not is a politically charged debate. To push for a code of conduct which doesn't recognize it is tantamount to pure agenda pushing."

Some things are so stupid it would be wearying to dignify them with consideration. There is no "reverse racism/sexism": there is sexism, racism or not.

**Comment by strugee** [comment]
Locking this issue because there's some obvious trolling. (For the record, I haven't deleted any tweets. Go ahead and archive all the non-existent material you want.)

As @cwebber said, this is a decision for the people in the project, in particular Evan, to make - not people who have nothing to do with the project besides having commented on this issue.

**Comment by evanp** [comment]
Hi. We're adopting this code of conduct. @strugee please do the PR.

**Comment by evanp** [comment]
Oh, and I totally appreciate the deep concern for the health of the pump.io community.

**Comment by larjona** [comment]
As per https://github.com/e14n/pump.io/wiki/Meeting-2016-02-19 , we are adopting the "Contributor Covenant" code of conduct: http://contributor-covenant.org/
