### ISSUE TITLE
Support for node.js v4 LTS

### ISSUE THREAD

**Issue by bernhardreiter** [e14n/pump.io#1164]
According to the https://github.com/nodejs/LTS#lts_schedule node 0.10 will
go out of maintenance in November this year. 

So it makes sense to add official support to the current LTS release of nodejs which is v4.

Form the source it looks like somebody runs pump.io from nodejs 0.12 as well,
what are your experiences? Does pump.io run out of the box?
Anyone tries v4.4?

**Comment by strugee** [comment]
I'm not in front of a desktop right now so I can't check, but IIRC the story here is that the code almost completely works, but we have a couple dependencies that need to be upgraded. That needs to happen anyway, so this should work out on its own.

Thanks for bringing this up.

**Comment by bernhardreiter** [comment]
Good news that you have already tried it!
We need to get rid of the "almost" before the "works" part then? >;)

As for updating dependencies, do you mean that you need to adjust the numbers
or will there be code changes?

To me it looks like it would make sense to create a gh-"fork" for a version that 
aims to run with v4 with current dependencies to become master eventually.

**Comment by strugee** [comment]
Sorry for the late reply.

All dependency upgrades require a major version increment which (because of semver) almost certainly means code changes. In particular, Express and Connect need upgrading.

I think creating a fork will probably be more trouble than it's worth, especially in terms of how easy it is to review. The "right" way to approach this is to upgrade dependencies one at a time, adjusting the code for breaking changes. I'd be thrilled to review PRs that do this.

**Comment by strugee** [comment]
The test suite is run against Node 4 in Travis now and we officially support it as a project; for all intents and purposes this effectively means we're done here. Closing.
